language: julia
julia:
  - 1.0
os:
  - linux
matrix:
    fast_finish: true

notifications:
    email: false

after_success:
  - julia -e 'cd(Pkg.dir("TuringBenchmarks")); Pkg.add("Coverage");
              using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using Pkg, TuringBenchmarks;
              cd(joinpath(dirname(pathof(TuringBenchmarks)), ".."));
              include(joinpath("docs", "make.jl"))'
notifications:
    email: false
