language: julia
julia:
  - 1.0
os:
  - linux
matrix:
    fast_finish: true

notifications:
    email: false

script:
  - julia --check-bounds=yes -e 'using Pkg;
                              Pkg.build("ContinuousBenchmarks");
                              Pkg.test("ContinuousBenchmarks"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ContinuousBenchmarks")); Pkg.add("Coverage");
              using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using Pkg, ContinuousBenchmarks;
              cd(joinpath(dirname(pathof(ContinuousBenchmarks)), ".."));
              include(joinpath("docs", "make.jl"))'
notifications:
    email: false
