[github]
# the information of the bot account
user = "TuringBenchBot"
email = "TuringBenchBot@email.com"
token = "PRIVATE_INFO"

# Benchmark reports will be committed to this repo
report_repo = "TuringLang/ContinuousBenchmarks.jl"
report_branch = "report"

[target]
# Target repository: we will run benchmarks for this repo
repo = "TuringLang/Turing.jl"
use_remote_branches = true
project_dir = "."
benchmark_files = "benchmarks/benchmark_list.jl"
