[github]
# the information of the bot account
user = "BayesBot"
email = "BayesBot@email.com"
token = "PRIVATE_INFO"

# Benchmark reports will be committed to this repo
report_repo = "TuringLang/ContinuousBenchmarks.jl"
report_branch = "report"

[target]
# Target repository: we will run benchmarks for this repo
repo = "TuringLang/Turing.jl"
use_remote_branches = true
project_dir = "."
benchmark_config_file = "benchmarks/benchmark_config.jl"
